# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1641, 965)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(222)
        sizePolicy.setVerticalStretch(222)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/图标/ooopic_1521110980.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/*ToolButton扁平化*/\n"
"QToolButton {\n"
"border:0px;\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDockNestingEnabled(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_37 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("")
        self.label_37.setMidLineWidth(0)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_2.addWidget(self.label_37)
        self.minimize = QtWidgets.QToolButton(self.centralWidget)
        self.minimize.setMinimumSize(QtCore.QSize(0, 0))
        self.minimize.setToolTipDuration(0)
        self.minimize.setStyleSheet("border：0px；")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/图标/Remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize.setIcon(icon1)
        self.minimize.setIconSize(QtCore.QSize(30, 30))
        self.minimize.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.minimize.setAutoRaise(True)
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.minimize)
        self.close_button = QtWidgets.QToolButton(self.centralWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/图标/Power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setIconSize(QtCore.QSize(30, 30))
        self.close_button.setAutoRaise(True)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_28.addWidget(self.label_31)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1540, 1299))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout.addWidget(self.label_34)
        self.line_33 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_33.setLineWidth(2)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setObjectName("line_33")
        self.horizontalLayout.addWidget(self.line_33)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_51 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_51.setMinimumSize(QtCore.QSize(180, 35))
        self.pushButton_51.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_51.setStyleSheet("")
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout.addWidget(self.pushButton_51, 0, 0, 1, 1)
        self.pushButton_66 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_66.setMinimumSize(QtCore.QSize(180, 35))
        self.pushButton_66.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_66.setFont(font)
        self.pushButton_66.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_66.setStyleSheet("")
        self.pushButton_66.setObjectName("pushButton_66")
        self.gridLayout.addWidget(self.pushButton_66, 0, 3, 1, 1)
        self.pushButton_65 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_65.setMinimumSize(QtCore.QSize(180, 35))
        self.pushButton_65.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_65.setFont(font)
        self.pushButton_65.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_65.setStyleSheet("")
        self.pushButton_65.setObjectName("pushButton_65")
        self.gridLayout.addWidget(self.pushButton_65, 0, 2, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_26.setEnabled(False)
        self.pushButton_26.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_26.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_46.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_46.addItem(spacerItem3)
        self.verticalLayout_45.addLayout(self.verticalLayout_46)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.label_30)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_5.addWidget(self.line_6)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_16.setEnabled(False)
        self.pushButton_16.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_16.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 0, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 0, 1, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_39.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_2.addWidget(self.pushButton_39, 1, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_18.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_2)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_4)
        self.tableWidget_3.setMaximumSize(QtCore.QSize(16777215, 96))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        self.horizontalLayout_8.addWidget(self.tableWidget_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_2.addWidget(self.line_13)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_2.addWidget(self.line_12)
        self.pushButton_27 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_27.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_27.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_27.setStyleSheet("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_2.addWidget(self.pushButton_27)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_13.addWidget(self.label_32)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_48 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_48.sizePolicy().hasHeightForWidth())
        self.pushButton_48.setSizePolicy(sizePolicy)
        self.pushButton_48.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_3.addWidget(self.pushButton_48, 0, 2, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_50.setEnabled(False)
        self.pushButton_50.setMinimumSize(QtCore.QSize(125, 35))
        self.pushButton_50.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_3.addWidget(self.pushButton_50, 0, 0, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_47.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_3.addWidget(self.pushButton_47, 1, 0, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_49.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_3.addWidget(self.pushButton_49, 1, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 0, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 1, 1, 1, 1)
        self.horizontalLayout_17.addLayout(self.gridLayout_3)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_4)
        self.tableWidget_7.setMaximumSize(QtCore.QSize(16777215, 96))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(4)
        self.tableWidget_7.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_7.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 1, item)
        self.horizontalLayout_17.addWidget(self.tableWidget_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 350))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.line_19 = QtWidgets.QFrame(self.widget_7)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_22.addWidget(self.line_19)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.verticalLayout_22)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.pushButton_41 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_41.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_41.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_41.setStyleSheet("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.verticalLayout_2.addWidget(self.pushButton_41)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_28.addWidget(self.scrollArea_4)
        self.tabWidget_3.addTab(self.tab_2, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.tab_9)
        self.label_36.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36, 0, QtCore.Qt.AlignRight)
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_8.addWidget(self.pushButton_19)
        self.line_9 = QtWidgets.QFrame(self.tab_9)
        self.line_9.setMinimumSize(QtCore.QSize(20, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_8.addWidget(self.line_9)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_7.addWidget(self.pushButton_20, 1, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_7.addWidget(self.pushButton_21, 2, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_4.setMinimumSize(QtCore.QSize(0, 87))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 1, item)
        self.gridLayout_7.addWidget(self.tableWidget_4, 1, 1, 2, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_9)
        self.label_38.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.line_14 = QtWidgets.QFrame(self.tab_9)
        self.line_14.setMinimumSize(QtCore.QSize(0, 10))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_8.addWidget(self.line_14)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_28.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_8.addWidget(self.pushButton_28)
        spacerItem7 = QtWidgets.QSpacerItem(20, 183, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.verticalLayout_3.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_4.sizePolicy().hasHeightForWidth())
        self.tabWidget_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_17)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_40 = QtWidgets.QLabel(self.tab_17)
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_9.addWidget(self.label_40)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.tab_17)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_33.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_33.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_5.addWidget(self.pushButton_33, 0, 0, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_38.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_38.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_5.addWidget(self.pushButton_38, 1, 0, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_25.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_5.addWidget(self.pushButton_25, 1, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_24.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_5.addWidget(self.pushButton_24, 0, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.tab_17)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_5.addWidget(self.line_10, 0, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.tab_17)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_5.addWidget(self.line_16, 1, 1, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_5)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_17)
        self.tableWidget_6.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(2)
        self.tableWidget_6.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_18.addWidget(self.tableWidget_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.line_7 = QtWidgets.QFrame(self.tab_17)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_9.addWidget(self.line_7)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_8 = QtWidgets.QLabel(self.tab_17)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_20.addWidget(self.label_8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.verticalLayout_20)
        self.line_15 = QtWidgets.QFrame(self.tab_17)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_9.addWidget(self.line_15)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_17)
        self.pushButton_29.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_29.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_29.setStyleSheet("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_9.addWidget(self.pushButton_29)
        self.tabWidget_4.addTab(self.tab_17, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_29.addWidget(self.label_23)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_52 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_52.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_52.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setObjectName("pushButton_52")
        self.horizontalLayout_15.addWidget(self.pushButton_52)
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_15.addWidget(self.label_41)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_15.addWidget(self.lineEdit_14)
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_15.addWidget(self.label_42)
        self.pushButton_53 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_53.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_53.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_53.setObjectName("pushButton_53")
        self.horizontalLayout_15.addWidget(self.pushButton_53)
        self.line_17 = QtWidgets.QFrame(self.tab_7)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_15.addWidget(self.line_17)
        self.pushButton_55 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_55.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_55.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_55.setObjectName("pushButton_55")
        self.horizontalLayout_15.addWidget(self.pushButton_55)
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_15.addWidget(self.label_49)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_15.addWidget(self.lineEdit_16)
        self.label_48 = QtWidgets.QLabel(self.tab_7)
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_15.addWidget(self.label_48)
        self.pushButton_54 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_54.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_54.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_54.setObjectName("pushButton_54")
        self.horizontalLayout_15.addWidget(self.pushButton_54)
        self.line_25 = QtWidgets.QFrame(self.tab_7)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_15.addWidget(self.line_25)
        self.pushButton_56 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_56.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_56.setObjectName("pushButton_56")
        self.horizontalLayout_15.addWidget(self.pushButton_56)
        self.pushButton_60 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_60.setMinimumSize(QtCore.QSize(133, 35))
        self.pushButton_60.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_60.setObjectName("pushButton_60")
        self.horizontalLayout_15.addWidget(self.pushButton_60)
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.verticalLayout_29.addLayout(self.horizontalLayout_15)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_7)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1540, 1088))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_31.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem12)
        self.verticalLayout_36.addLayout(self.verticalLayout_31)
        self.verticalLayout_37.addWidget(self.widget_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(0, 600))
        self.widget.setObjectName("widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_30.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem14)
        self.gridLayout_9.addLayout(self.verticalLayout_30, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 600))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_32.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem16)
        self.gridLayout_11.addLayout(self.verticalLayout_32, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.widget_2)
        self.verticalLayout_37.addLayout(self.horizontalLayout_10)
        self.pushButton_42 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_42.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_42.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_42.setStyleSheet("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.verticalLayout_37.addWidget(self.pushButton_42)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_29.addWidget(self.scrollArea)
        self.tabWidget_4.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.tabWidget_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_12.addWidget(self.pushButton_22)
        self.label_51 = QtWidgets.QLabel(self.tab_10)
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_12.addWidget(self.label_51)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_12.addWidget(self.lineEdit_17)
        self.label_50 = QtWidgets.QLabel(self.tab_10)
        self.label_50.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_12.addWidget(self.label_50)
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_23.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_12.addWidget(self.pushButton_23)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_5.setMinimumSize(QtCore.QSize(200, 68))
        self.tableWidget_5.setMaximumSize(QtCore.QSize(16777215, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        self.verticalLayout_4.addWidget(self.tableWidget_5)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.tab_10)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem18)
        self.verticalLayout_4.addLayout(self.verticalLayout_18)
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.tab_6)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_8)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1516, 922))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 900))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_44 = QtWidgets.QLabel(self.widget_6)
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_44.setFont(font)
        self.label_44.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_16.addWidget(self.label_44)
        self.pushButton_40 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_40.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_40.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_40.setStyleSheet("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_16.addWidget(self.pushButton_40)
        self.pushButton_59 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_59.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_59.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_59.setStyleSheet("")
        self.pushButton_59.setObjectName("pushButton_59")
        self.horizontalLayout_16.addWidget(self.pushButton_59)
        self.line_18 = QtWidgets.QFrame(self.widget_6)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setLineWidth(5)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_16.addWidget(self.line_18)
        self.label_43 = QtWidgets.QLabel(self.widget_6)
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_16.addWidget(self.label_43)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_30.setMinimumSize(QtCore.QSize(180, 50))
        self.pushButton_30.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_30.setStyleSheet("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_16.addWidget(self.pushButton_30)
        self.line_11 = QtWidgets.QFrame(self.widget_6)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_16.addWidget(self.line_11)
        self.pushButton_31 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_31.setEnabled(False)
        self.pushButton_31.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_31.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_31.setToolTip("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_16.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_32.setEnabled(False)
        self.pushButton_32.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_32.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_32.setToolTip("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_16.addWidget(self.pushButton_32)
        self.line_26 = QtWidgets.QFrame(self.widget_6)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_16.addWidget(self.line_26)
        self.pushButton_57 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_57.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_57.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_57.setStyleSheet("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.horizontalLayout_16.addWidget(self.pushButton_57)
        self.pushButton_58 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_58.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_58.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_58.setStyleSheet("")
        self.pushButton_58.setObjectName("pushButton_58")
        self.horizontalLayout_16.addWidget(self.pushButton_58)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        self.verticalLayout_44.addLayout(self.horizontalLayout_16)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_5.setFont(font)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.tab_13)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tab_13)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem20)
        self.verticalLayout_33.addLayout(self.verticalLayout_7)
        self.tabWidget_5.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.tab_14)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.tab_14)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem21)
        self.verticalLayout_34.addLayout(self.verticalLayout_10)
        self.tabWidget_5.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.tab_15)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.tab_15)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem22)
        self.verticalLayout_35.addLayout(self.verticalLayout_12)
        self.tabWidget_5.addTab(self.tab_15, "")
        self.verticalLayout_44.addWidget(self.tabWidget_5)
        self.verticalLayout_23.addWidget(self.widget_6)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_43.addWidget(self.scrollArea_3)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.tab_11)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_34.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_34.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_34.setStyleSheet("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_7.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_35.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_35.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_35.setStyleSheet("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_7.addWidget(self.pushButton_35)
        self.pushButton_62 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_62.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_62.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_62.setFont(font)
        self.pushButton_62.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_62.setStyleSheet("")
        self.pushButton_62.setObjectName("pushButton_62")
        self.horizontalLayout_7.addWidget(self.pushButton_62)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.verticalLayout_39.addLayout(self.horizontalLayout_7)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_11)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 66, 1222))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 1200))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_21.addItem(spacerItem24)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem25)
        self.verticalLayout_40.addLayout(self.verticalLayout_21)
        self.verticalLayout_25.addWidget(self.widget_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_39.addWidget(self.scrollArea_2)
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.tab_12)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_36 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_36.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_36.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_36.setStyleSheet("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_3.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_37.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_37.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_37.setStyleSheet("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_3.addWidget(self.pushButton_37)
        self.pushButton_63 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_63.setMinimumSize(QtCore.QSize(160, 50))
        self.pushButton_63.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_63.setStyleSheet("")
        self.pushButton_63.setObjectName("pushButton_63")
        self.horizontalLayout_3.addWidget(self.pushButton_63)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.verticalLayout_27.addLayout(self.horizontalLayout_3)
        self.line_21 = QtWidgets.QFrame(self.tab_12)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_27.addWidget(self.line_21)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_20 = QtWidgets.QLabel(self.tab_12)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_26.addWidget(self.label_20)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem27)
        self.verticalLayout_27.addLayout(self.verticalLayout_26)
        self.tabWidget_2.addTab(self.tab_12, "")
        self.verticalLayout_24.addWidget(self.tabWidget_2)
        self.verticalLayout_6.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_16)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_16)
        self.tabWidget_6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget_6.setFont(font)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_19)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_43 = QtWidgets.QPushButton(self.tab_19)
        self.pushButton_43.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_43.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_43.setStyleSheet("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_9.addWidget(self.pushButton_43)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_9.addWidget(self.lineEdit_12)
        self.pushButton_44 = QtWidgets.QPushButton(self.tab_19)
        self.pushButton_44.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_44.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_44.setStyleSheet("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_9.addWidget(self.pushButton_44)
        self.verticalLayout_19.addLayout(self.horizontalLayout_9)
        self.line_23 = QtWidgets.QFrame(self.tab_19)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_19.addWidget(self.line_23)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.tab_19)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem28)
        self.verticalLayout_19.addLayout(self.verticalLayout_14)
        self.tabWidget_6.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_20)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_45 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_45.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_45.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_45.setStyleSheet("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_11.addWidget(self.pushButton_45)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_11.addWidget(self.lineEdit_13)
        self.pushButton_46 = QtWidgets.QPushButton(self.tab_20)
        self.pushButton_46.setMinimumSize(QtCore.QSize(150, 50))
        self.pushButton_46.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_46.setStyleSheet("")
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_11.addWidget(self.pushButton_46)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.line_24 = QtWidgets.QFrame(self.tab_20)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_16.addWidget(self.line_24)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_7 = QtWidgets.QLabel(self.tab_20)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem29)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.tabWidget_6.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.tab_21)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_9 = QtWidgets.QLabel(self.tab_21)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_42.addWidget(self.label_9)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_24 = QtWidgets.QLabel(self.tab_21)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_19.addWidget(self.label_24)
        self.comboBox = QtWidgets.QComboBox(self.tab_21)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox)
        self.pushButton_61 = QtWidgets.QPushButton(self.tab_21)
        self.pushButton_61.setMinimumSize(QtCore.QSize(300, 50))
        self.pushButton_61.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_61.setStyleSheet("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.horizontalLayout_19.addWidget(self.pushButton_61)
        self.pushButton_64 = QtWidgets.QPushButton(self.tab_21)
        self.pushButton_64.setMinimumSize(QtCore.QSize(300, 50))
        self.pushButton_64.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_64.setFont(font)
        self.pushButton_64.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_64.setStyleSheet("")
        self.pushButton_64.setObjectName("pushButton_64")
        self.horizontalLayout_19.addWidget(self.pushButton_64)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem30)
        self.verticalLayout_42.addLayout(self.horizontalLayout_19)
        self.widget_5 = QtWidgets.QWidget(self.tab_21)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem31)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_38.addItem(spacerItem32)
        self.verticalLayout_41.addLayout(self.verticalLayout_38)
        self.verticalLayout_42.addWidget(self.widget_5)
        self.tabWidget_6.addTab(self.tab_21, "")
        self.verticalLayout_17.addWidget(self.tabWidget_6)
        self.tabWidget.addTab(self.tab_16, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.minimize.clicked.connect(MainWindow.showMinimized)
        self.close_button.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "电磁数据采集与信号识别"))
        self.label_37.setText(_translate("MainWindow", "       电磁数据采集与信号识别"))
        self.minimize.setToolTip(_translate("MainWindow", "最小化"))
        self.minimize.setText(_translate("MainWindow", "..."))
        self.close_button.setToolTip(_translate("MainWindow", "关闭"))
        self.close_button.setText(_translate("MainWindow", "..."))
        self.label_33.setText(_translate("MainWindow", "IQ识别"))
        self.label_34.setText(_translate("MainWindow", "自动识别"))
        self.label_25.setText(_translate("MainWindow", "采集文件存储路径D:\\postgraduate_program\\usrp_recvfiles\\;识别结果输出路径D:\\postgraduate_program\\IqOutput\\"))
        self.pushButton_51.setText(_translate("MainWindow", "检测仪器连接状况"))
        self.pushButton_66.setText(_translate("MainWindow", "超频点识别"))
        self.pushButton_65.setText(_translate("MainWindow", "超频点查看"))
        self.pushButton_26.setText(_translate("MainWindow", "usrp信号采集"))
        self.label_30.setText(_translate("MainWindow", "手动识别"))
        self.label_19.setText(_translate("MainWindow", "采集文件存储路径D:\\postgraduate_program\\usrp_recvfiles\\;识别结果输出路径D:\\postgraduate_program\\IqOutput\\"))
        self.pushButton_16.setText(_translate("MainWindow", "usrp信号采集"))
        self.pushButton_17.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_39.setText(_translate("MainWindow", "在线识别"))
        self.pushButton_18.setText(_translate("MainWindow", "离线识别"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "信号名称"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "中心频率(MHz)"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "带宽(Hz)"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "调制方式"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "频点识别"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_27.setText(_translate("MainWindow", "记录上传"))
        self.label_32.setText(_translate("MainWindow", "包络识别"))
        self.label_21.setText(_translate("MainWindow", "    存储路径D:\\postgraduate_program\\specEnvelope_recvfiles\\"))
        self.pushButton_48.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_50.setText(_translate("MainWindow", "usrp信号采集"))
        self.pushButton_47.setText(_translate("MainWindow", "在线识别"))
        self.pushButton_49.setText(_translate("MainWindow", "离线识别"))
        item = self.tableWidget_7.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "信号名称"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "识别结果"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "相似度"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "起止频率"))
        __sortingEnabled = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        self.tableWidget_7.setSortingEnabled(__sortingEnabled)
        self.pushButton_41.setText(_translate("MainWindow", "记录上传"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("MainWindow", "USRP信号采集与识别"))
        self.label_36.setText(_translate("MainWindow", "pico信号采集"))
        self.pushButton_19.setText(_translate("MainWindow", "pico信号采集"))
        self.pushButton_20.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_21.setText(_translate("MainWindow", "开始识别"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "信号名称"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "信号频率"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "信号幅度"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "调制方式"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.label_38.setText(_translate("MainWindow", "pico数据识别"))
        self.pushButton_28.setText(_translate("MainWindow", "记录上传"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "pico信号采集与识别"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "电磁干扰信号"))
        self.label_40.setText(_translate("MainWindow", "（建议采集10次数据）"))
        self.label_22.setText(_translate("MainWindow", "存储路径D:\\postgraduate_program\\interference_file\\txt\\"))
        self.pushButton_33.setText(_translate("MainWindow", "pico信号采集"))
        self.pushButton_38.setText(_translate("MainWindow", "在线识别"))
        self.pushButton_25.setText(_translate("MainWindow", "离线识别"))
        self.pushButton_24.setText(_translate("MainWindow", "选择文件"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件夹名称"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "信号类型"))
        self.pushButton_29.setText(_translate("MainWindow", "记录上传"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "开关脉冲识别"))
        self.label_23.setText(_translate("MainWindow", "采集文件存储路径D:\\postgraduate_program\\steadyStateInterference_recvfiles\\;识别结果输出路径D:\\postgraduate_program\\steadyInterference\\Output_file\\"))
        self.pushButton_52.setText(_translate("MainWindow", "信号采集"))
        self.label_41.setText(_translate("MainWindow", "输入限值"))
        self.label_42.setText(_translate("MainWindow", "dBm"))
        self.pushButton_53.setText(_translate("MainWindow", "范围选定"))
        self.pushButton_55.setText(_translate("MainWindow", "选择文件"))
        self.label_49.setText(_translate("MainWindow", "输入限值"))
        self.label_48.setText(_translate("MainWindow", "dBm"))
        self.pushButton_54.setText(_translate("MainWindow", "范围选定"))
        self.pushButton_56.setText(_translate("MainWindow", "历史查看"))
        self.pushButton_60.setText(_translate("MainWindow", "刷新"))
        self.pushButton_42.setText(_translate("MainWindow", "记录上传"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("MainWindow", "稳态干扰识别"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "信号流识别"))
        self.pushButton_22.setText(_translate("MainWindow", "选择文件"))
        self.label_51.setText(_translate("MainWindow", "输入带宽"))
        self.label_50.setText(_translate("MainWindow", "M"))
        self.pushButton_23.setText(_translate("MainWindow", "开始判断信噪比"))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "信号名称"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "信噪比"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "判断信噪比"))
        self.label_44.setText(_translate("MainWindow", "10K~200MHz"))
        self.pushButton_40.setText(_translate("MainWindow", "pico信号采集"))
        self.pushButton_59.setText(_translate("MainWindow", "pico数据库清空"))
        self.label_43.setText(_translate("MainWindow", "200M~5GHz"))
        self.pushButton_30.setText(_translate("MainWindow", "检测仪器连接状况"))
        self.pushButton_31.setText(_translate("MainWindow", "USRP1信号采集"))
        self.pushButton_32.setText(_translate("MainWindow", "USRP2信号采集"))
        self.pushButton_57.setText(_translate("MainWindow", "USRP1数据库清空"))
        self.pushButton_58.setText(_translate("MainWindow", "USRP2数据库清空"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_13), _translate("MainWindow", "usrp1"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), _translate("MainWindow", "usrp2"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_15), _translate("MainWindow", "pico"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "频域监测"))
        self.pushButton_34.setText(_translate("MainWindow", "数据采集"))
        self.pushButton_35.setText(_translate("MainWindow", "绘图"))
        self.pushButton_62.setText(_translate("MainWindow", "数据清空"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "时域监测"))
        self.pushButton_36.setText(_translate("MainWindow", "数据采集"))
        self.pushButton_37.setText(_translate("MainWindow", "绘图"))
        self.pushButton_63.setText(_translate("MainWindow", "数据清空"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("MainWindow", "实时频谱仪"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "实时监测"))
        self.pushButton_43.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_44.setText(_translate("MainWindow", "绘图"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_19), _translate("MainWindow", "时域波形绘图工具"))
        self.pushButton_45.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_46.setText(_translate("MainWindow", "绘图"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_20), _translate("MainWindow", "频域波形绘图工具"))
        self.label_9.setText(_translate("MainWindow", "注：本页面仅用于采集，采集结束后请在D:\\postgraduate_program\\antenna_recv\\路径下找到采集文件并使用信号流识别标签下的稳态干扰识别功能进行比对。"))
        self.label_24.setText(_translate("MainWindow", "一体化单元选择："))
        self.comboBox.setItemText(0, _translate("MainWindow", "一体化单元一"))
        self.comboBox.setItemText(1, _translate("MainWindow", "一体化单元二"))
        self.comboBox.setItemText(2, _translate("MainWindow", "一体化单元一、二"))
        self.pushButton_61.setText(_translate("MainWindow", "前后向天线信号采集"))
        self.pushButton_64.setText(_translate("MainWindow", "效果比对图查看"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_21), _translate("MainWindow", "天线效果比对工具"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("MainWindow", "工具"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "系统介绍"))

import ziyuan_rc
